// <auto-generated />
using Grayson.ExampleCQRS.Ritten.Infrastructure.ReadModel.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Grayson.ExampleCQRS.Ritten.Infrastructure.Migrations
{
    [DbContext(typeof(ReadModelDbContext))]
    [Migration("20180323145757_InititalCreate")]
    partial class InititalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Grayson.ExampleCQRS.Ritten.Domain.ReadModel.Model.KmStandView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AdresId");

                    b.Property<DateTime>("Datum");

                    b.Property<int>("Stand");

                    b.HasKey("Id");

                    b.ToTable("KmStand");
                });

            modelBuilder.Entity("Grayson.ExampleCQRS.Ritten.Domain.ReadModel.Model.RitView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BeginStand");

                    b.Property<Guid>("BeginStandId");

                    b.Property<int>("EindStand");

                    b.Property<Guid>("EindStandId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Ritten");
                });
#pragma warning restore 612, 618
        }
    }
}
