version: '3.6'

services:
  grayson.examplecqrs.kmstanden.host.consoleapp:
    image: graysonexamplecqrskmstandenhostconsoleapp
    build:
      context: ./Grayson.ExampleCQRS.KmStanden.Host.ConsoleApp
      #dockerfile: ./Grayson.ExampleCQRS.KmStanden.Host.ConsoleApp/Dockerfile
    depends_on:
      - rabbitmq
#
  grayson.examplecqrs.kmstanden.webapi:
    image: graysonexamplecqrskmstandenwebapi
    build:
      context: ./Grayson.ExampleCQRS.KmStanden.WebApi
      #dockerfile: 
    depends_on:
      - rabbitmq
      - events.data

  grayson.examplecqrs.ritten.host.consoleapp:
    image: graysonexamplecqrsrittenhostconsoleapp
    build:
      context: ./Grayson.ExampleCQRS.Ritten.Host.ConsoleApp
      #dockerfile: Grayson.ExampleCQRS.Ritten.Host.ConsoleApp/Dockerfile
    depends_on:
      - rabbitmq
      - events.data
      - sql.data

  grayson.examplecqrs.readmodel.host.consoleapp:
    image: graysonexamplecqrsreadmodelhostconsoleapp
    build:
      context: ./Grayson.ExampleCQRS.Readmodel.Host.ConsoleApp
      #dockerfile: Grayson.ExampleCQRS.Readmodel.Host.ConsoleApp/Dockerfile
    depends_on:
      - rabbitmq
      - sql.data

  grayson.examplecqrs.readmodel.wepapi:
    image: graysonexamplecqrsreadmodelwepapi
    build:
      context: ./Grayson.ExampleCQRS.ReadModel.WepApi
      #dockerfile: Grayson.ExampleCQRS.ReadModel.WepApi/Dockerfile

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - sqlvolume:/var/opt/mssql

  events.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  webcoreangular:
    image: webcoreangular
    build:
      context: .
      #dockerfile: WebCoreAngular/Dockerfile

volumes:
  sqlvolume:


