version: '3'

services:
  grayson.examplecqrs.kmstanden.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=guest
      - EventBusPassword=guest
    ports:
      - "6001:80"

  grayson.examplecqrs.kmstanden.host.consoleapp:
    environment:
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=guest
      - EventBusPassword=guest

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"