version: '3'

services:
  grayson.examplecqrs.kmstanden.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=guest
      - EventBusPassword=guest
      - CommandBusConnection=rabbitmq://${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}:5672
      - CommandBusUserName=guest
      - CommandBusPassword=guest
    ports:
      - "6001:80"

  grayson.examplecqrs.kmstanden.host.consoleapp:
    environment:
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=guest
      - EventBusPassword=guest
      - CommandBusConnection=rabbitmq://${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}:5672
      - CommandBusUserName=guest
      - CommandBusPassword=guest
      - MongoDbUri=mongodb://events.data:27017

  grayson.examplecqrs.ritten.host.consoleapp:
    environment:
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=guest
      - EventBusPassword=guest
      - CommandBusConnection=rabbitmq://${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}:5672
      - CommandBusUserName=guest
      - CommandBusPassword=guest
      - MongoDbUri=mongodb://events.data:27017
      - SqlDbConnection=${ESHOP_AZURE_IDENTITY_DB:-Server=sql.data;Database=Microsoft.eShopOnContainers.Service.IdentityDb;User Id=sa;Password=Pass@word} 


  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
#
  events.data:
    ports:
      - "27017:27017"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"