version: '3.4'

services:
  grayson.examplecqrs.kmstanden.host.consoleapp:
    image: graysonexamplecqrskmstandenhostconsoleapp
    build:
      context: .
      dockerfile: Grayson.ExampleCQRS.KmStanden.Host.ConsoleApp/Dockerfile
    depends_on:
      - rabbitmq
#
  grayson.examplecqrs.kmstanden.webapi:
    image: graysonexamplecqrskmstandenwebapi
    build:
      context: .
      dockerfile: Grayson.ExampleCQRS.KmStanden.WebApi/Dockerfile
    depends_on:
      - rabbitmq
      - events.data

  grayson.examplecqrs.ritten.host.consoleapp:
    image: graysonexamplecqrsrittenhostconsoleapp
    build:
      context: .
      dockerfile: Grayson.ExampleCQRS.Ritten.Host.ConsoleApp/Dockerfile
    depends_on:
      - rabbitmq
      - events.data
      - sql.data

#  grayson.examplecqrs.readmodel.host.consoleapp:
#    image: graysonexamplecqrsreadmodelhostconsoleapp
#    build:
#      context: .
#      dockerfile: Grayson.ExampleCQRS.Readmodel.Host.ConsoleApp/Dockerfile
#    depends_on:
#      - rabbitmq

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - sqlvolume:/var/opt/mssql

  events.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

volumes:
  sqlvolume: