version: '3'

services:
  grayson.examplecqrs.kmstanden.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=rabbitmq://10.0.75.1:5672/
      - EventBusUserName=guest
      - EventBusPassword=guest
    ports:
      - "6001:80"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"