name: .NET build

on:
  push:
    branches: 
       - main
       - release/*
  pull_request:
    branches: 
       - main
       - release/*
env:
  target: debug
  SOLUTION_FILE_PATH: ./*.sln

jobs:
  build:
    env:
      target: debug

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Environment Variables from Dotenv
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $SOLUTION_FILE_PATH
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
