name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        global-json-file: /global.json
    - run: dotnet build Grayson.ExampleCQRS.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal
